### ISSUE TITLE
Laravel 5.5 Auto Package Discovery

### ISSUE THREAD

**Issue by lloy0076** [web-chefs/QueueButler#1]
This package may benefit from auto package discovery:

https://laravel.com/docs/5.5/packages#package-discovery

**Comment by JFossey** [comment]
Yes, thanks for the reminder, we plan on testing in 5.5 shortly and will then look at Package Discovery.

@lloy0076 were you able to use the artisan command `queue:batch` in 5.5.

**Comment by JFossey** [comment]
Laravel 5.5 is as of version 1.1 fully supported including package discovery c03b9779af3c77237b993665726bd055b1e05e22.
